// @ts-nocheck -- skip type checking
import * as docs_7 from "../content/docs/release-history.mdx?collection=docs&hash=1777176138453"
import * as docs_6 from "../content/docs/project-structure.mdx?collection=docs&hash=1777176138453"
import * as docs_5 from "../content/docs/index.mdx?collection=docs&hash=1777176138453"
import * as docs_4 from "../content/docs/getting-started.mdx?collection=docs&hash=1777176138453"
import * as docs_3 from "../content/docs/environment-management.mdx?collection=docs&hash=1777176138453"
import * as docs_2 from "../content/docs/deployment-config.mdx?collection=docs&hash=1777176138453"
import * as docs_1 from "../content/docs/concepts.mdx?collection=docs&hash=1777176138453"
import * as docs_0 from "../content/docs/application-management.mdx?collection=docs&hash=1777176138453"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"application-management.mdx","absolutePath":"/Users/wangzhaobin/Desktop/项目/DeployX/docs/content/docs/application-management.mdx"}, data: docs_0 }, { info: {"path":"concepts.mdx","absolutePath":"/Users/wangzhaobin/Desktop/项目/DeployX/docs/content/docs/concepts.mdx"}, data: docs_1 }, { info: {"path":"deployment-config.mdx","absolutePath":"/Users/wangzhaobin/Desktop/项目/DeployX/docs/content/docs/deployment-config.mdx"}, data: docs_2 }, { info: {"path":"environment-management.mdx","absolutePath":"/Users/wangzhaobin/Desktop/项目/DeployX/docs/content/docs/environment-management.mdx"}, data: docs_3 }, { info: {"path":"getting-started.mdx","absolutePath":"/Users/wangzhaobin/Desktop/项目/DeployX/docs/content/docs/getting-started.mdx"}, data: docs_4 }, { info: {"path":"index.mdx","absolutePath":"/Users/wangzhaobin/Desktop/项目/DeployX/docs/content/docs/index.mdx"}, data: docs_5 }, { info: {"path":"project-structure.mdx","absolutePath":"/Users/wangzhaobin/Desktop/项目/DeployX/docs/content/docs/project-structure.mdx"}, data: docs_6 }, { info: {"path":"release-history.mdx","absolutePath":"/Users/wangzhaobin/Desktop/项目/DeployX/docs/content/docs/release-history.mdx"}, data: docs_7 }], [{"info":{"path":"meta.json","absolutePath":"/Users/wangzhaobin/Desktop/项目/DeployX/docs/content/docs/meta.json"},"data":{"title":"DeployX 文档","pages":["---入门---","getting-started","index","concepts","project-structure","---使用指南---","application-management","deployment-config","environment-management","release-history"]}}])